Login and SignUp Activity added.
NJACKWinterOfCode/RoboTalk pull request #17
Opened 2019-12-03 11:26 UTC by Sarthak2601

Fixes #8 and #9 

Changes: 
---- Code Additions -----
-Integrated Firebase in the App.
-Sign Up through Email and Password.
-Log-in Activity through Email and Password.
-Log-out Button Added in HomeActivity for Signing out. 
-Also added the feature which checks if the user has logged in the app in past and logs him/her in straightaway. 
---- UI Connections ----- 
*Connected Splash Screen with Log-in Activity.
*Connected Log-in Activity with Sign-Up Activity.
*Connected Log-in Activity with Home Activity. 
*Connected Home Activity with Log-in Activity when Log-out button is clicked.

Screenshots for the change:
![Screenshot_2019-12-03-16-52-13-812_io github njackwinterofcode robotalk](https://user-images.githubusercontent.com/53938155/70047260-b701c380-15ed-11ea-88e5-0a5b75ca813b.png)
![Screenshot_2019-12-03-16-52-19-173_io github njackwinterofcode robotalk](https://user-images.githubusercontent.com/53938155/70047261-b701c380-15ed-11ea-980a-4448f7860b03.png)
![Screenshot_2019-12-03-16-52-38-555_io github njackwinterofcode robotalk](https://user-images.githubusercontent.com/53938155/70047263-b79a5a00-15ed-11ea-8db5-8c15ba18b0f7.png)

2019-12-03 13:51 UTC, somenath1435 commented
@Sarthak2601 Add somenath1435@gmail.com in firebase

2019-12-03 13:54 UTC, somenath1435 requested changes

2019-12-03 13:54 UTC, somenath1435 commented on app/src/main/java/io/github/njackwinterofcode/robotalk/LoginActivity.java
> +
Remove unnecessary spaces

2019-12-03 13:54 UTC, somenath1435 commented on app/src/main/java/io/github/njackwinterofcode/robotalk/LoginActivity.java
> +
there are many unncessary spaces in your PR, remove all

2019-12-03 13:54 UTC, somenath1435 commented on app/src/main/res/layout/activity_login.xml
> +        android:text="Log-in"
use strings.xml instead of hardcoding

2019-12-04 21:15 UTC, somenath1435 commented
@Sarthak2601 Still some files contain unnecessary spaces/lines. Remove all

2019-12-05 17:55 UTC, Sarthak2601 commented
> @Sarthak2601 Add [somenath1435@gmail.com](mailto:somenath1435@gmail.com) in firebase

Do you mean adding this email account to the Auth database so that you can log in? If yes then you can make it through Sign up Activity. If otherwise, please elaborate.

2019-12-05 18:18 UTC, Sarthak2601 commented
@somenath1435 Changes done.

2019-12-07 17:53 UTC, merged