feat: IncludesCI Script
NJACKWinterOfCode/RoboTalk pull request #32
Opened 2019-12-18 10:34 UTC by s-ayush2903

**Fixes #14** 
**Changes:** A simple config.yaml file was written as CI script

**Screenshots for the change:** N/A

2019-12-18 10:48 UTC, ShivangiSingh17 requested changes
Add Travis CI also as per mentioned in the #14

2019-12-19 10:18 UTC, ShivangiSingh17 reviewed
make the file name to be .travis.yml

2019-12-19 10:42 UTC, ShivangiSingh17 commented on travis.yml
> +  - chmod +x ./gradlew
Please parse yml files through [YAML Formatter,](https://jsonformatter.org/yaml-formatter) the merged .travis.yml had basic syntax issues. Please make sure it passes [YAML Lint ](http://www.yamllint.com/)before committing further changes.

YML is a very unforgiving language, it looks deeply into indentation and stuff just like Python. Be sure, and careful :)

2019-12-19 10:49 UTC, ShivangiSingh17 commented on .travis.yml
> +  - chmod +x ./gradlew
Please parse yml files through YAML Formatter, the merged .travis.yml had basic syntax issues. Please make sure it passes YAML Lint before committing further changes.

YML is a very unforgiving language, it looks deeply into indentation and stuff just like Python. Be sure, and careful :)

2019-12-22 13:13 UTC, s-ayush2903 commented
@somenath1435 please review

2019-12-22 14:07 UTC, ShivangiSingh17 approved these changes

2019-12-22 14:07 UTC, merged